<?php
$db['orders'] = array(
  'columns' => 
    array (
        'cid' => array(
            'type' => 'int(10)',
            'pkey' => true,
            'extra' => 'auto_increment',
            'required' => true,
            'label' => '编号',
            'filterdefault' => false,
            'in_list' => false,
            'default_in_list' => false,
            'width' => 60,
            'hidden' => true,
            'order'=>5,
        ),
        'order_id' => array (
            'type' => 'int unsigned',
            'default' => '0',
            'required' => true,
            'in_list' => false,
            'label' => '订单ID',
            'width' => 100,
            'order'=>10,
        ),
        'order_bn' => array (
          'type' => 'varchar(32)',
          'label' => '订单号',
          'is_title' => true,
          'required' => true,
          'searchtype' => 'nequal',
          'filtertype' => 'normal',
          'filterdefault' => false,
          'in_list' => true,
          'default_in_list' => true,
          'width' => 180,
          'order'=>15,
        ),
        'declare_bn' => array (
          'type' => 'varchar(32)',
          'label' => '申报单号',
          'is_title' => true,
          'searchtype' => 'nequal',
          'filtertype' => 'normal',
          'filterdefault' => false,
          'in_list' => true,
          'default_in_list' => true,
          'width' => 150,
          'order'=>20,
        ),
        'shop_type' => array (
          'type' => 'varchar(20)',
          'label' => '购物网站',
          'width' => 75,
          'in_list' => false,
          'filtertype' => 'normal',
          'filterdefault' => false,
          'order'=>60,
        ),
        'card_no' => array (
          'type' => 'varchar(20)',
          'label' => '身份证号',
          'width' => 75,
          'in_list' => false,
          'filtertype' => 'normal',
          'filterdefault' => false,
          'order'=>35,
        ),
        'payment_bn' => array (
          'type' => 'varchar(50)',
          'label' => '支付单号',
          'width' => 170,
          'searchtype' => 'has',
          'filtertype' => 'yes',
          'filterdefault' => false,
          'in_list' => true,
          'default_in_list' => true,
          'is_title' => true,
          'order'=>30,
        ),
        'payment' => array (
          'type' => 'char(10)',
          'label' => '支付方式',
          'width' => 80,
          'in_list' => false,
          'default_in_list' => false,
          'order'=>45,
        ),
        'currency' => array (
          'type' => 'char(10)',
          'label' => '货币',
          'width' => 65,
          'in_list' => false,
          'default_in_list' => false,
          'order'=>50,
        ),
        't_end' => array (
          'type' => 'time',
          'label' => '支付完成时间',
          'width' => 110,
          'editable' => false,
          'in_list' => false,
          'required' => false,
          'default' => 0,
          'order'=>55,
        ),
        'member_id' => array (
              'type' => 'int unsigned',
              'label' => '会员ID',
              'width' => 75,
              'editable' => false,
              'in_list' => false,
              'required' => true,
              'default' => 0,
              'order'=>64,
        ),
        'member_uname' => array (
              'type' => 'varchar(50)',
              'label' => '用户名',
              'width' => 80,
              'in_list' => true,
              'default_in_list' => true,
              'order'=>65,
        ),
        'member_name' => array (
              'type' => 'varchar(50)',
              'label' => '姓名',
              'width' => 60,
              'in_list' => false,
              'default_in_list' => false,
              'order'=>70,
        ),
        'member_mobile' => array (
              'type' => 'varchar(30)',
              'label' => '手机',
              'width' => 60,
              'in_list' => false,
              'default_in_list' => false,
              'order'=>75,
        ),
        'member_tel' => array (
              'type' => 'varchar(30)',
              'label' => '固定电话',
              'width' => 60,
              'in_list' => false,
              'default_in_list' => false,
              'order'=>80,
        ),
        'member_email' => array (
              'type' => 'varchar(200)',
              'label' => '邮箱',
              'width' => 110,
              'in_list' => false,
              'default_in_list' => false,
              'order'=>85,
        ),
        'logis_id' => array (
              'type' => 'int unsigned',
              'default' => '0',
              'in_list' => false,
              'default_in_list' => false,
              'label' => '物流公司',
              'width' => 60,
              'order'=>100,
        ),
        'logis_no' => array (
              'type' => 'varchar(50)',
              'label' => '物流运单号',
              'width' =>130,
              'in_list' => true,
              'default_in_list' => true,
              'order'=>105,
        ),
        'status' => array(
              'type' => array(
                      0 => '待申报',
                      1 => '已申报',
                      2 => '申报中',
                      3 => '已撤消',
                      4 => '已拒绝',
              ),
              'default' => '0',
              'required' => true,
              'label' => '申报状态',
              'filtertype' => 'normal',
              'filterdefault' => true,
              'in_list' => true,
              'default_in_list' => true,
              'width' => 80,
              'order'=>60,
        ),
        'declare_check' => array(
              'type' => array(
                      0 => '未通过',
                      1 => '已通过',
                  ),
              'default' => '0',
              'required' => true,
              'label' => '申报单校验',
              'filtertype' => 'normal',
              'filterdefault' => true,
              'in_list' => true,
              'default_in_list' => true,
              'width' => 80,
              'order'=>64,
        ),
        'declare_status' => array(
              'type' => 'char(10)',
              'label' => '申报单状态',
              'width' => 100,
              'in_list' => false,
              'default_in_list' => false,
              'order'=>65,
        ),
        'apply_pay' => array(
              'type' => 'tinyint(2)',
              'default' => '0',
              'label' => '申请支付单',
              'order'=>152,
              'in_list' => false,
              'default_in_list' => false,
        ),
        'apply_lgs' => array(
              'type' => 'tinyint(2)',
              'default' => '0',
              'label' => '申请运单',
              'order'=>152,
              'in_list' => false,
              'default_in_list' => false,
        ),
        'disabled' => array (
            'type' => 'bool',
            'label' => '是否有效',
            'required' => true,
            'default' => 'false',
            'in_list' => false,
            'default_in_list' => false,
        ),
        'remarks' => array(
          'type' => 'text',
          'label' => '申报备注',
        ),
        'op_id' =>array (
          'type' => 'table:account@pam',
          'default' => '0',
          'label' => '操作员',
          'editable' => false,
          'width' => 60,
          'filtertype' => 'normal',
          'filterdefault' => false,
          'in_list' => false,
          'default_in_list' => false,
          'order'=>115,
        ),
        'shop_sid' => array (
            'type' => 'int unsigned',
            'label' => '跨境电子口岸',
            'width' => 75,
            'in_list' => false,
            'default' => 0,
            'order'=>118,
        ),
        'dateline' => array(
          'type' => 'time',
          'label' => '添加日期',
          'filtertype' => 'time',
          'filterdefault' => true,
          'in_list' => true,
          'default_in_list' => true,
          'width' => 130,
          'order'=>180,
        ),
        'lastdate' => array(
          'type' => 'time',
          'label' => '申报日期',
          'filtertype' => 'time',
          'filterdefault' => true,
          'in_list' => false,
          'default_in_list' => false,
          'width' => 130,
          'order'=>190,
        ),
  ),
  'index' => array(
        'order_id'=>array(
            'columns'=>array(
                0=>'order_id',
            ),
        ),
        'order_bn'=>array(
            'columns'=>array(
                0=>'order_bn',
            ),
        ),
        'status' => array(
            'columns'=>array(
                0=>'status',
            ),
        ),
    ),
  'engine' => 'innodb',
  'version' => '$Rev: 150416 $',
);