<?php
$db['setting']=array(
    'columns' =>
        array(
            'sid' => array(
                'type' => 'smallint(6)',
                'required' => true,
                'pkey' => true,
                'extra' => 'auto_increment',
                'label' => '编号',
                'in_list' => false,
                'default_in_list' => false,
                'width' => 60,
                'hidden' => true,
                'order' => 10,
            ),
            'company_id' => array (
                    'type' => 'int unsigned',
                    'default' => '0',
                    'required' => true,
                    'in_list' => false,
                    'default_in_list' => false,
                    'label' => '电子口岸',
                    'width' => 120,
                    'order'=>15,
            ),
            'company_code' => array(
                'type' => 'varchar(32)',
                'filterdefault' => true,
                'in_list' => true,
                'default_in_list' => true,
                'label' => '企业代码',
                'order' => 20,
            ),
            'company_name' => array(
                'type' => 'varchar(50)',
                'filterdefault' => true,
                'in_list' => true,
                'default_in_list' => true,
                'label' => '企业名称',
                'order' => 30,
            ),
            'custom_type' => array(
                'type' => array(
                    1 => '保税备货',
                    2 => '保税集货',
                    3 => '一般进口',
                ),
                'default' => '1',
                'required' => true,
                'label' => '业务类型',
                'filtertype' => 'normal',
                'filterdefault' => true,
                'in_list' => true,
                'default_in_list' => true,
                'width' => 100,
                'order'=>40,
            ),
            'shop_id' => array(
                'type' => 'varchar(100)',
                'comment' => '渠道所属店铺',
                'label' => '主店铺',
                'order' => 50,
            ),
            'username' => array(
                'type' => 'varchar(32)',
                'filterdefault' => true,
                'in_list' => true,
                'default_in_list' => true,
                'label' => '账号',
                'order' => 60,
            ),
            'password' => array(
                'type' => 'varchar(50)',
                'label' => '密钥',
                'in_list' => false,
                'order' => 70,
            ),
            'bind_status' => array(
                'type' => 'bool',
                'required' => true,
                'default' => 'false',
                'filterdefault' => true,
                'in_list' => true,
                'default_in_list' => true,
                'label' => '绑定状态',
                'order' => 80,
            ),
            'disabled' => array (
                'type' => 'bool',
                'label' => '无效',
                'required' => false,
                'filterdefault' => false,
                'in_list' => false,
                'default_in_list' => false,
                'default' => 'false',
                'order' => 90,
            ),
            'dateline' => array(
                'type' => 'time',
                'label' => '添加日期',
                'width' => 130,
                'in_list' => true,
                'default_in_list' => true,
                'filtertype' => 'time',
                'filterdefault' => true,
                'order' => 95,
            ),
            'lastdate' => array(
                'type' => 'time',
                'label' => '最后更新日期',
                'width' => 130,
                'in_list' => true,
                'default_in_list' => true,
                'filtertype' => 'time',
                'filterdefault' => true,
                'order' => 99,
            ),
            'branch_ids' => array(
                'type' => 'serialize',
                'in_list' => false,
                'default_in_list' => false,
                'label' => '仓库',
                'order' => 50,
            ),
    ),
    'engine' => 'innodb',
    'version' => '$Rev:  $',
);